export const GET_TYPE_PRODUCT="GET_TYPE_PRODUCT";
export const ADD_TO_CART="ADD_TO_CART";
export const REMOTE_FROM_CART="REMOTE_FROM_CART";
export const SAVE_BILL="SAVE_BILL";
export const REMOVE_ALL_ITEM_IN_CARTS="REMOVE_ALL_ITEM_IN_CARTS";